#
# Copyright 2023 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM ubuntu:latest
RUN mkdir -p /work/tests
RUN mkdir -p /work/test-results/functional


RUN export DEBIAN_FRONTEND=noninteractive ;\
    apt-get update ;\
    apt-get install -y --no-install-recommends apt-utils ;\
    apt-get install -y locales ;\
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8;\
    apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev git python-is-python3 python3-distutils python3-pip

ENV LANG en_US.utf8

COPY dist /work/dist
COPY tests/ui/pytest-ci.ini /work/pytest.ini
RUN pip install /work/dist/*.whl
RUN pip install pytest-splunk-addon
RUN pip install pytest-expect
RUN pip install pytest-rerunfailures
COPY tests/entrypoint.sh /
COPY tests /work/tests
COPY tests/ui/.pytest.expect /work/.pytest.expect
RUN cd /work/tests && ls
RUN cd ../..

WORKDIR /work

ENTRYPOINT "/entrypoint.sh"
